"""updated meals

Revision ID: 43202993966d
Revises: 9f603ee01c8f
Create Date: 2023-03-29 08:26:54.487386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43202993966d'
down_revision = '9f603ee01c8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('starch_profile', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('spice_profile', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('dairy_profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'dairy_profile')
    op.drop_column('meals', 'spice_profile')
    op.drop_column('meals', 'starch_profile')
    # ### end Alembic commands ###
