"""updated meals

Revision ID: c7febf40a85b
Revises: 43202993966d
Create Date: 2023-03-29 11:14:24.596775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7febf40a85b'
down_revision = '43202993966d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('meals', 'region')
    op.drop_column('meals', 'has_meat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('has_meat', sa.BOOLEAN(), nullable=True))
    op.add_column('meals', sa.Column('region', sa.VARCHAR(), nullable=True))
    op.drop_column('meals', 'name')
    # ### end Alembic commands ###
