"""new attribute names

Revision ID: c9579f6f59d0
Revises: cfb91cb539ab
Create Date: 2023-03-29 14:57:27.004584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9579f6f59d0'
down_revision = 'cfb91cb539ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('starch_type', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('spice_type', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('dairy_type', sa.String(), nullable=True))
    op.drop_column('meals', 'dairy_profile')
    op.drop_column('meals', 'spice_profile')
    op.drop_column('meals', 'starch_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('starch_profile', sa.VARCHAR(), nullable=True))
    op.add_column('meals', sa.Column('spice_profile', sa.VARCHAR(), nullable=True))
    op.add_column('meals', sa.Column('dairy_profile', sa.VARCHAR(), nullable=True))
    op.drop_column('meals', 'dairy_type')
    op.drop_column('meals', 'spice_type')
    op.drop_column('meals', 'starch_type')
    # ### end Alembic commands ###
