"""added  wine name

Revision ID: cfb91cb539ab
Revises: c7febf40a85b
Create Date: 2023-03-29 12:53:50.324695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb91cb539ab'
down_revision = 'c7febf40a85b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wines', sa.Column('name', sa.String(), nullable=True))
    op.add_column('wines', sa.Column('wine_type', sa.String(), nullable=True))
    op.drop_column('wines', 'grape_varietal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wines', sa.Column('grape_varietal', sa.VARCHAR(), nullable=True))
    op.drop_column('wines', 'wine_type')
    op.drop_column('wines', 'name')
    # ### end Alembic commands ###
